# Dockerfile for Devcontainer
# https://hub.docker.com/r/microsoft/devcontainers-python/
# Replace with node:24 in the future
FROM mcr.microsoft.com/devcontainers/typescript-node:22

USER node

COPY --chown=node:node . /workspace
