name: "show-achiever"

services:
  backend:
    build:
      context: ./../../
      dockerfile: .devcontainer/backend/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - backend-data:/workspace

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
  backend-data:
