# Generated by Django 5.1.6 on 2025-02-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achiever_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventadmin",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_administrators",
                to="achiever_app.event",
                verbose_name="Events",
            ),
        ),
    ]
