# Generated by Django 5.1.6 on 2025-02-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achiever_app", "0002_eventadmin_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="following_event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendees",
                to="achiever_app.event",
                verbose_name="Following Event",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendee",
            name="telegram_id",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
