# Generated by Django 5.1.6 on 2025-02-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achiever_app", "0003_attendee_following_event_alter_attendee_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendee",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Attendee",
                "verbose_name_plural": "Attendees",
            },
        ),
        migrations.AlterModelOptions(
            name="attendeewallet",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Attendee Wallet",
                "verbose_name_plural": "Attendee Wallets",
            },
        ),
        migrations.AlterModelOptions(
            name="attendeewalletbalance",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Attendee Wallet Balance",
                "verbose_name_plural": "Attendee Wallet Balances",
            },
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="eventadmin",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Event Admin",
                "verbose_name_plural": "Event Admins",
            },
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
        migrations.AlterModelOptions(
            name="goalbalance",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Goal Balance",
                "verbose_name_plural": "Goal Balances",
            },
        ),
        migrations.AlterModelOptions(
            name="goaltransaction",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Goal Transaction",
                "verbose_name_plural": "Goal Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="partnertask",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Partner Task",
                "verbose_name_plural": "Partner Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="partnertaskitem",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at",),
                "verbose_name": "Partner Task Item",
                "verbose_name_plural": "Partner Task Items",
            },
        ),
    ]
